
## Analysing Pharma Sales Data
What are the total sales quantities for each drug category (ATC code)?

Which individual drug brands have the highest total sales?

Which three drugs have the highest sales in January 2015, July 2016, September 2017.

Which drug has sold the most often in 2017?

Which drug category has the highest average daily sales?

Are respiratory drugs (R03) sold more during specific months?

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [16]:
monthly_sales = pd.read_csv('./data/salesmonthly.csv')

In [17]:
daily_sales = pd.read_csv('./data/salesdaily.csv')

In [ ]:
hourly_sales = pd.read_csv('./data/saleshourly.csv')

In [19]:
weekly_sales = pd.read_csv('./data/salesweekly.csv')

In [25]:
def check_basics(df):
    print('*'*40, 'Missing Values','*'*40)
    print(daily_sales.isna().sum())

    print('*'*40, 'Duplicates','*'*40)
    print(daily_sales.duplicated().sum())

    print('*'*40, 'Shape','*'*40)
    print(daily_sales.shape)

    print('*'*40, 'Statistical Checks','*'*40)
    print(daily_sales.describe().T)

In [ ]:
check_basics(daily_sales)

In [ ]:
hourly_sales.head()

In [ ]:
weekly_sales.head()

In [35]:
monthly_sales.head()

        datum   M01AB    M01AE    N02BA     N02BE   N05B  N05C    R03    R06
0  2014-01-31  127.69   99.090  152.100   878.030  354.0  50.0  112.0   48.2
1  2014-02-28  133.32  126.050  177.000  1001.900  347.0  31.0  122.0   36.2
2  2014-03-31  137.44   92.950  147.655   779.275  232.0  20.0  112.0   85.4
3  2014-04-30  113.10   89.475  130.900   698.500  209.0  18.0   97.0   73.7
4  2014-05-31  101.79  119.933  132.100   628.780  270.0  23.0  107.0  123.7

In [ ]:
# What are the total sales quantities for each drug category (ATC code)?
print(monthly_sales.sum(numeric_only=True))

In [50]:
# Which individual drug brands have the highest total sales?
highest_sales = monthly_sales.sum(numeric_only=True).max()
print(highest_sales)

# N02BE has the highest sales with 62477.945

62477.94500000001

In [119]:
monthly_sales.head()

       datum   M01AB    M01AE    N02BA     N02BE   N05B  N05C    R03    R06
0 2014-01-31  127.69   99.090  152.100   878.030  354.0  50.0  112.0   48.2
1 2014-02-28  133.32  126.050  177.000  1001.900  347.0  31.0  122.0   36.2
2 2014-03-31  137.44   92.950  147.655   779.275  232.0  20.0  112.0   85.4
3 2014-04-30  113.10   89.475  130.900   698.500  209.0  18.0   97.0   73.7
4 2014-05-31  101.79  119.933  132.100   628.780  270.0  23.0  107.0  123.7

In [ ]:
# Which three drugs have the highest sales in January 2015, July 2016, September 2017.

# Concert column datum to date type
monthly_sales['datum'] = pd.to_datetime(monthly_sales['datum'])


jan_sales = (monthly_sales[
    (monthly_sales['datum'].dt.year == 2015) & 
    (monthly_sales['datum'].dt.month == 1)
])

july_sales = (monthly_sales[
    (monthly_sales['datum'].dt.year == 2016) & 
    (monthly_sales['datum'].dt.month == 7)
])
sept_sales = (monthly_sales[
    (monthly_sales['datum'].dt.year == 2017) & 
    (monthly_sales['datum'].dt.month == 9)
])

print(jan_sales.sum(numeric_only=True).sort_values(ascending=False).head(3))
print(july_sales.sum(numeric_only=True).sort_values(ascending=False).head(3))
print(sept_sales.sum(numeric_only=True).sort_values(ascending=False).head(3))

# Drugs with the higest sales in January 2015:
    # N02BE: 1044.24
    # N05B: 463.00
    # M01AB: 177.25

# Drugs with the higest sales in July 2016:
    # N02BE: 652.362
    # N05B: 240.000
    # M01AB: 203.970

# Drugs with the higest sales in September 2017:
# N02BE: 863.75
# N05B: 223.00
# R03: 139.00

In [146]:
daily_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 2106 entries, 0 to 2105
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   datum         2106 non-null   str
 1   M01AB         2106 non-null   float64
 2   M01AE         2106 non-null   float64
 3   N02BA         2106 non-null   float64
 4   N02BE         2106 non-null   float64
 5   N05B          2106 non-null   float64
 6   N05C          2106 non-null   float64
 7   R03           2106 non-null   float64
 8   R06           2106 non-null   float64
 9   Year          2106 non-null   int64
 10  Month         2106 non-null   int64
 11  Hour          2106 non-null   int64
 12  Weekday Name  2106 non-null   str
dtypes: float64(8), int64(3), str(2)
memory usage: 214.0 KB

In [149]:
daily_sales.head()

,datum,M01AB,M01AE,N02BA,N02BE,N05B,N05C,R03,R06,Year,Month,Hour,Weekday Name
0,1/2/2014,0.0,3.67,3.4,32.40,7.0,0.0,0.0,2.0,2014,1,248,Thursday
1,1/3/2014,8.0,4.00,4.4,50.60,16.0,0.0,20.0,4.0,2014,1,276,Friday
2,1/4/2014,2.0,1.00,6.5,61.85,10.0,0.0,9.0,1.0,2014,1,276,Saturday
3,1/5/2014,4.0,3.00,7.0,41.10,8.0,0.0,3.0,0.0,2014,1,276,Sunday
4,1/6/2014,5.0,1.00,4.5,21.70,16.0,2.0,6.0,2.0,2014,1,276,Monday

In [ ]:
# Which drug has sold the most often in 2017?

sales_2017 = daily_sales[(daily_sales['Year'] == 2017)]
print(sales_2017[['M01AB', 'M01AE', 'N02BA', 'N02BE',
        'N05B', 'N05C', 'R03', 'R06']].sum(numeric_only=True).sort_values(ascending=False).head(1))

# The N02BE drug has sold the most in 2017 with 9258.80

N02BE    9258.804833
dtype: float64

In [ ]:
print(monthly_sales.info())

In [ ]:
# Which drug category has the highest average daily sales?
print(
    daily_sales[['M01AB', 'M01AE', 'N02BA', 'N02BE', 'N05B', 'N05C', 'R03', 'R06']].mean().
    sort_values(ascending=False).head(1))

# N02BE has the highest average daily sales 29.917095

N02BE    29.917095
dtype: float64

In [ ]:
# Are respiratory drugs (R03) sold more during specific months?
r03_sales = daily_sales[['R03', 'Month']]
r03_sales.groupby('Month').sum()

# R03 are sold more in the first three months

In [99]:
daily_sales.head()

,datum,M01AB,M01AE,N02BA,N02BE,N05B,N05C,R03,R06,Year,Month,Hour,Weekday Name
0,1/2/2014,0.0,3.67,3.4,32.40,7.0,0.0,0.0,2.0,2014,1,248,Thursday
1,1/3/2014,8.0,4.00,4.4,50.60,16.0,0.0,20.0,4.0,2014,1,276,Friday
2,1/4/2014,2.0,1.00,6.5,61.85,10.0,0.0,9.0,1.0,2014,1,276,Saturday
3,1/5/2014,4.0,3.00,7.0,41.10,8.0,0.0,3.0,0.0,2014,1,276,Sunday
4,1/6/2014,5.0,1.00,4.5,21.70,16.0,2.0,6.0,2.0,2014,1,276,Monday